import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_PATH || 'C:/Users/ASUS/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const base = process.env.TEST_URL || 'http://localhost:5173';
const browser = await chromium.launch({ channel: 'chrome', headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage();
page.setDefaultTimeout(7000);
const errors = [];
page.on('pageerror', e => errors.push(e.message));
const go = async route => { await page.goto(base + route); await page.locator('#root').waitFor(); await page.waitForTimeout(100); };
const read = key => page.evaluate(key => JSON.parse(localStorage.getItem(key)), key);
try {
  for (const route of ['/', '/faq', '/contact', '/register', '/student/dashboard', '/student/application', '/student/application/selection', '/student/application/confirmation', '/student/payment', '/student/applications', '/student/admission', '/student/results', '/student/results/veena-diploma', '/student/status', '/student/ceremony', '/examiner/dashboard', '/examiner/examinations', '/examiner/evaluations', '/examiner/settings', '/examiner/notifications', '/admin/dashboard', '/admin/applications', '/admin/workflow/APP-2024-001', '/admin/configurations', '/admin/users', '/admin/results', '/admin/ceremony', '/admin/email-logs', '/admin/system-health', '/admin/audit-logs', '/admin/security', '/admin/access-control']) {
    await go(route); assert.ok((await page.locator('#root').innerText()).length > 50, route);
  }
  console.log('PASS 32 combined routes');
  await go('/student/dashboard');
  await page.getByRole('button', { name: /New Application/ }).click();
  await page.getByLabel('Candidate Full Name').fill('Sanjay Krishnan');
  await page.getByPlaceholder('MM/DD/YYYY').fill('01202000');
  assert.equal(await page.getByPlaceholder('MM/DD/YYYY').inputValue(), '01/20/2000');
  await page.getByLabel('Exam Level').selectOption('Grade 3');
  await page.getByLabel('Select Registered Teacher').selectOption({ index: 1 });
  const canvas = await page.locator('canvas').boundingBox();
  await page.mouse.move(canvas.x + 20, canvas.y + 40); await page.mouse.down();
  await page.mouse.move(canvas.x + 100, canvas.y + 65, { steps: 12 }); await page.mouse.up();
  await page.getByRole('button', { name: 'Next Page' }).click();
  await page.locator('label.subject-option').first().click();
  assert.equal(await page.getByRole('checkbox').first().isChecked(), true);
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  await page.getByRole('button', { name: 'Proceed to Payment' }).click();
  await page.getByLabel('Cardholder Name').fill('Sanjay Krishnan');
  await page.getByLabel('Card Number').fill('4242424242424242');
  await page.getByLabel('Expiry Date').fill('12/30');
  await page.getByLabel('CVV', { exact: true }).fill('123');
  await page.getByRole('button', { name: 'Confirm & Pay' }).click();
  await page.getByRole('heading', { name: 'Payment Successful' }).waitFor();
  await page.getByRole('button', { name: 'Continue', exact: true }).click();
  const student = await read('musicExamStudentPortal');
  const application = student.applications[0];
  assert.equal(application.paymentStatus, 'Paid');
  assert.ok(!JSON.stringify(student).includes('4242424242424242'));
  console.log('PASS A student application and simulated payment');
  await go('/admin/applications?q=' + application.id);
  await page.getByRole('button', { name: /Manage|View Details/ }).first().click();
  assert.match(await page.getByRole('dialog').innerText(), /Sanjay Krishnan/);
  await page.getByRole('button', { name: 'Approve and Assign' }).click();
  assert.ok(page.url().includes(application.id));
  console.log('PASS F student application handoff and same-ID workflow');
  // Use the actual application's subject and candidate identity for the seeded examiner session.
  await go('/examiner/dashboard');
  await page.evaluate(app => {
    const state = JSON.parse(localStorage.getItem('music-examiner-v1'));
    const session = state.sessions.find(s => s.id === 'EX-2024-0017');
    session.subject = app.subjects[0]; session.level = app.grade;
    session.candidates.forEach(c => { c.marks = '80'; });
    session.candidates[0].applicationId = app.id;
    localStorage.setItem('music-examiner-v1', JSON.stringify(state));
  }, application);
  await page.reload();
  await page.getByRole('article').filter({ hasText: 'Raga Hall' }).getByRole('button', { name: 'Continue Grading' }).click();
  await page.getByRole('textbox', { name: 'Marks for Sanjay Krishnan', exact: true }).fill('93');
  await page.getByRole('button', { name: 'SAVE AS DRAFT', exact: true }).click();
  await page.getByRole('button', { name: 'SUBMIT RESULTS TO ADMIN' }).click();
  await page.getByRole('button', { name: 'Return to Edit' }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Marks for Sanjay Krishnan', exact: true }).inputValue(), '93');
  await page.getByRole('button', { name: 'SUBMIT RESULTS TO ADMIN' }).click();
  await page.getByRole('button', { name: 'Confirm & Submit' }).click();
  await page.getByRole('dialog', { name: 'Evaluation Finalized Successfully' }).waitFor();
  console.log('PASS B examiner draft and submission');
  await go('/admin/results');
  const row = page.locator('tbody tr').filter({ hasText: 'EX-2024-0017' });
  assert.equal(await row.getByRole('switch').getAttribute('aria-checked'), 'false');
  await row.getByRole('button', { name: 'Review & Edit' }).click();
  await page.getByLabel('Marks for Sanjay Krishnan', { exact: true }).fill('96');
  await page.getByRole('button', { name: 'Save Review' }).click();
  await row.getByRole('switch').click();
  assert.equal(await row.getByRole('switch').getAttribute('aria-checked'), 'true');
  const resultId = 'published-EX-2024-0017-BHA-5-1';
  await go('/student/results');
  assert.match(await page.locator('.results-grid').innerText(), /96/);
  await go('/student/results/' + resultId);
  assert.match(await page.locator('.detail-hero').innerText(), /96/);
  await go('/admin/results');
  await page.locator('tbody tr').filter({ hasText: 'EX-2024-0017' }).getByRole('switch').click();
  assert.equal((await read('music-examiner-v1')).sessions.find(s => s.id === 'EX-2024-0017').candidates[0].marks, '96');
  await go('/student/results/' + resultId);
  await page.getByRole('heading', { name: 'Result unavailable' }).waitFor();
  console.log('PASS C/D/E submitted, reviewed, published, withdrawn without deletion');
  await go('/admin/configurations');
  await page.getByLabel('Fee for Foundation Grade (1-3)', { exact: true }).fill('135');
  assert.equal((await read('music-admin-v1')).feeLevels[0].fee, 135);
  await page.getByRole('button', { name: 'Venues', exact: true }).click();
  await page.getByRole('button', { name: 'Add New Venue' }).click();
  await page.getByLabel('Venue Name', { exact: true }).fill('QA Recital Hall');
  await page.getByLabel('Location', { exact: true }).fill('East Wing');
  await page.getByLabel('Capacity', { exact: true }).fill('80');
  await page.getByRole('button', { name: 'Save Venue' }).click();
  assert.ok((await read('music-admin-v1')).venues.some(v => v.name === 'QA Recital Hall'));
  await page.getByRole('button', { name: 'Time Slots', exact: true }).click();
  await page.getByRole('button', { name: 'Add New Template' }).click();
  await page.getByLabel('Template Name', { exact: true }).fill('QA Session');
  await page.getByLabel('Description', { exact: true }).fill('Practical examinations');
  await page.getByRole('dialog').getByLabel('Start Time').fill('10:00');
  await page.getByRole('dialog').getByLabel('End Time').fill('11:00');
  await page.getByRole('dialog').getByLabel('Venue', { exact: true }).fill('QA Recital Hall');
  await page.getByRole('button', { name: 'Save Template' }).click();
  assert.ok((await read('music-admin-v1')).timeTemplates.some(t => t.name === 'QA Session'));
  await go('/admin/users');
  for (const tab of ['Teachers', 'Examiners', 'Invigilators']) { await page.getByRole('button', { name: tab, exact: true }).click(); assert.ok(await page.locator('tbody tr').count()); }
  await page.getByRole('button', { name: 'Add New User' }).click();
  await page.getByLabel('Full Name', { exact: true }).fill('Test Invigilator');
  await page.getByLabel('Email', { exact: true }).fill('test@example.com');
  await page.getByLabel('Assigned Role', { exact: true }).fill('Lead Invigilator');
  await page.getByRole('button', { name: 'Add User', exact: true }).click();
  await page.getByPlaceholder('Search for Name / Role').fill('Test Invigilator');
  assert.equal(await page.locator('tbody tr').count(), 1);
  await page.getByRole('button', { name: 'Actions for Test Invigilator' }).click();
  await page.getByRole('button', { name: 'View / Edit' }).click();
  await page.getByLabel('Assigned Role', { exact: true }).fill('Session Marshal');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  assert.match(await page.locator('tbody').innerText(), /Session Marshal/);
  console.log('PASS G/H configuration and role tabs');
  await go('/admin/ceremony');
  await page.getByRole('button', { name: 'Edit Sanjay Krishnan', exact: true }).click();
  await page.getByLabel('Ceremony Session').selectOption('cs2');
  await page.getByRole('button', { name: 'Save Changes' }).click();
  const admin = await read('music-admin-v1');
  assert.ok(admin.ceremonyAttendance.filter(a => a.accountId === 'ACC-1000').every(a => a.sessionId === 'cs2'));
  await page.evaluate(() => { const s = JSON.parse(localStorage.getItem('music-admin-v1')); s.ceremonyAttendance[3].passed = false; localStorage.setItem('music-admin-v1', JSON.stringify(s)); });
  await page.reload();
  await page.getByRole('button', { name: 'Edit Kavya Natarajan', exact: true }).click();
  await page.getByRole('button', { name: 'Save Changes' }).click();
  await page.getByText('Only passing candidates may be allocated to a ceremony session.').waitFor();
  console.log('PASS I ceremony eligibility and account grouping');
  await go('/admin/email-logs');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Export', exact: true }).click();
  assert.equal((await downloadPromise).suggestedFilename(), 'email-logs.csv');
  const emailRow = page.locator('tbody tr').filter({ hasText: 'm.valencia@music-inst.org' });
  await emailRow.getByRole('button', { name: 'Manual Retry' }).click();
  await page.waitForTimeout(8500);
  const log = (await read('music-admin-v1')).emailLogs.find(e => e.id === 'e2');
  assert.equal(log.attempts, 3); assert.equal(log.status, 'Undeliverable / Admin Review');
  console.log('PASS J retry limit');
  assert.deepEqual(errors, []);
  console.log('PASS no fatal browser errors');
} finally { await browser.close(); }
